twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals: 
        websiteData: '@App\Service\GlobalVariablesCatcher'
        websitePages: '@App\Service\GlobalPagesCatcher'

when@test:
    twig:
        strict_variables: true
