vich_uploader:
    db_driver: orm

    mappings:
        website_images:
            uri_prefix: /uploads/website
            upload_destination: '%kernel.project_dir%/public/uploads/website'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        programme_images:
            uri_prefix: /uploads/programme
            upload_destination: '%kernel.project_dir%/public/uploads/programme'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        logo_images:
            uri_prefix: /uploads/logos
            upload_destination: '%kernel.project_dir%/public/uploads/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        partners_images:
            uri_prefix: /uploads/partners
            upload_destination: '%kernel.project_dir%/public/uploads/partners'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
